import { DEFAULT_COMPATIBILITY_DATE, DEFAULT_ROUTE } from './constants'
import { escapeTomlString } from './toml-utils'
import type { ResolvedEnvironment } from './types'

// This helper is here for the "no environments yet" case.
// It writes a small default route section.
// We need this so first-time users still get a valid wrangler file.
export function getNoEnvironmentSection(): string {
  return `
# No environments found yet, so a default route is used.
routes = [{ pattern = "${escapeTomlString(DEFAULT_ROUTE)}", custom_domain = true }]
`.trim()
}

// This helper is here to build one branch section at a time.
// It writes the env name and route, and it adds observability only when samplingRate is provided.
// We need this so logs are opt-in per environment.
export function getEnvironmentSection(
  appName: string,
  environment: ResolvedEnvironment,
): string {
  const observabilityBlock = environment.samplingRate === undefined
    ? ''
    : `

[env.${environment.name}.observability]
enabled = true
head_sampling_rate = ${environment.samplingRate}
`

  return `
# Branch: ${environment.branch}
[env.${environment.name}]
name = "${escapeTomlString(`${appName}-${environment.name}`)}"
routes = [
  { pattern = "${escapeTomlString(environment.routePattern)}", custom_domain = true }
]${observabilityBlock}
`.trim()
}

// This helper is here to build the main section of wrangler.toml.
// It writes the app name, main file, compatibility date, and optional account id.
// We need this to keep these core settings consistent in one place.
export function getHeaderBlock(appName: string): string {
  return `
# Generated by @nuxtlib/deployment-cf-workers.
# This file is generated from your \`cfDeployment\` module config.

name = "${escapeTomlString(appName)}"
main = ".output/server/index.mjs"
compatibility_date = "${DEFAULT_COMPATIBILITY_DATE}"
`.trim()
}
